version: 2
jobs:
  build:
    working_directory: ~/esa_feeder
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run:
          name: run bundle install
          command: bundle install
      - run:
          name: run test
          command: bundle exec rspec spec/
